spring:
  application:
    name: finflow
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  paths-to-match: /api/**
  paths-to-exclude: /api/health
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
